In [5]:
import pandas as pd
import numpy as np

In [7]:
fifa = pd.read_csv('players_22.csv')

In [4]:
fifa.head()

,sofifa_id,player_url,short_name,long_name,player_positions,overall,potential,value_eur,wage_eur,age,...,lcb,cb,rcb,rb,gk,player_face_url,club_logo_url,club_flag_url,nation_logo_url,nation_flag_url
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,"RW, ST, CF",93,93,78000000.0,320000.0,34,...,50+3,50+3,50+3,61+3,19+3,https://cdn.sofifa.net/players/158/023/22_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,https://cdn.sofifa.net/teams/1369/60.png,https://cdn.sofifa.net/flags/ar.png
1,188545,https://sofifa.com/player/188545/robert-lewand...,R. Lewandowski,Robert Lewandowski,ST,92,92,119500000.0,270000.0,32,...,60+3,60+3,60+3,61+3,19+3,https://cdn.sofifa.net/players/188/545/22_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/1353/60.png,https://cdn.sofifa.net/flags/pl.png
2,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"ST, LW",91,91,45000000.0,270000.0,36,...,53+3,53+3,53+3,60+3,20+3,https://cdn.sofifa.net/players/020/801/22_120.png,https://cdn.sofifa.net/teams/11/60.png,https://cdn.sofifa.net/flags/gb-eng.png,https://cdn.sofifa.net/teams/1354/60.png,https://cdn.sofifa.net/flags/pt.png
3,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Júnior,"LW, CAM",91,91,129000000.0,270000.0,29,...,50+3,50+3,50+3,62+3,20+3,https://cdn.sofifa.net/players/190/871/22_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,NaN,https://cdn.sofifa.net/flags/br.png
4,192985,https://sofifa.com/player/192985/kevin-de-bruy...,K. De Bruyne,Kevin De Bruyne,"CM, CAM",91,91,125500000.0,350000.0,30,...,69+3,69+3,69+3,75+3,21+3,https://cdn.sofifa.net/players/192/985/22_120.png,https://cdn.sofifa.net/teams/10/60.png,https://cdn.sofifa.net/flags/gb-eng.png,https://cdn.sofifa.net/teams/1325/60.png,https://cdn.sofifa.net/flags/be.png

In [292]:
# Handling missing values

for c in fifa.columns:
    print('{} -   {}%'.format(c,round((np.mean(fifa[c].isnull()))*100)))

sofifa_id -   0%
player_url -   0%
short_name -   0%
long_name -   0%
player_positions -   0%
overall -   0%
potential -   0%
value_eur -   0%
wage_eur -   0%
age -   0%
dob -   0%
height_cm -   0%
weight_kg -   0%
club_team_id -   0%
club_name -   0%
league_name -   0%
league_level -   0%
club_position -   0%
club_jersey_number -   0%
club_loaned_from -   94%
club_joined -   6%
club_contract_valid_until -   0%
nationality_id -   0%
nationality_name -   0%
nation_team_id -   96%
nation_position -   96%
nation_jersey_number -   96%
preferred_foot -   0%
weak_foot -   0%
skill_moves -   0%
international_reputation -   0%
work_rate -   0%
body_type -   0%
real_face -   0%
release_clause_eur -   6%
player_tags -   93%
player_traits -   51%
pace -   11%
shooting -   11%
passing -   11%
dribbling -   11%
defending -   11%
physic -   11%
attacking_crossing -   0%
attacking_finishing -   0%
attacking_heading_accuracy -   0%
attacking_short_passing -   0%
attacking_volleys -   0%
skill_dribbling -   0%
skill_curve -   0%
skill_fk_accuracy -   0%
skill_long_passing -   0%
skill_ball_control -   0%
movement_acceleration -   0%
movement_sprint_speed -   0%
movement_agility -   0%
movement_reactions -   0%
movement_balance -   0%
power_shot_power -   0%
power_jumping -   0%
power_stamina -   0%
power_strength -   0%
power_long_shots -   0%
mentality_aggression -   0%
mentality_interceptions -   0%
mentality_positioning -   0%
mentality_vision -   0%
mentality_penalties -   0%
mentality_composure -   0%
defending_marking_awareness -   0%
defending_standing_tackle -   0%
defending_sliding_tackle -   0%
goalkeeping_diving -   0%
goalkeeping_handling -   0%
goalkeeping_kicking -   0%
goalkeeping_positioning -   0%
goalkeeping_reflexes -   0%
goalkeeping_speed -   89%
ls -   0%
st -   0%
rs -   0%
lw -   0%
lf -   0%
cf -   0%
rf -   0%
rw -   0%
lam -   0%
cam -   0%
ram -   0%
lm -   0%
lcm -   0%
cm -   0%
rcm -   0%
rm -   0%
lwb -   0%
ldm -   0%
cdm -   0%
rdm -   0%
rwb -   0%
lb -   0%
lcb -   0%
cb -   0%
rcb -   0%
rb -   0%
gk -   0%
player_face_url -   0%
club_logo_url -   0%
club_flag_url -   0%
nation_logo_url -   96%
nation_flag_url -   0%

In [293]:
col = []
for c in fifa.columns:
    missingVal = np.mean(fifa[c].isnull())*100
    if missingVal > 60:
        print('{} - {}%'.format(c, round(missingVal)))
        col.append(c)
print("\n")
print('Columns needed to drop :  \n\n',col)

club_loaned_from - 94%
nation_team_id - 96%
nation_position - 96%
nation_jersey_number - 96%
player_tags - 93%
goalkeeping_speed - 89%
nation_logo_url - 96%


Columns needed to drop :

 ['club_loaned_from', 'nation_team_id', 'nation_position', 'nation_jersey_number', 'player_tags', 'goalkeeping_speed', 'nation_logo_url']

In [294]:
fifa.drop(columns = ['club_loaned_from',
 'nation_team_id',
 'nation_position',
 'nation_jersey_number',
 'player_tags',
 'goalkeeping_speed',
 'nation_logo_url'] ,inplace = True)

In [295]:
print("After handling the missing values, the dataset has : ",fifa.shape[0],"rows and " ,fifa.shape[1],"columns")

After handling the missing values, the dataset has :  19239 rows and  103 columns

In [296]:
# Counting columns with missing values Null Values
null_sum = fifa.isnull().sum()
null_sum[null_sum > 0]

value_eur                      74
wage_eur                       61
club_team_id                   61
club_name                      61
league_name                    61
league_level                   61
club_position                  61
club_jersey_number             61
club_joined                  1163
club_contract_valid_until      61
release_clause_eur           1176
player_traits                9841
pace                         2132
shooting                     2132
passing                      2132
dribbling                    2132
defending                    2132
physic                       2132
club_logo_url                  61
club_flag_url                  61
dtype: int64

In [297]:
def fill_na(col):
    if col.dtype == 'float64':
        return col.fillna(col.mean())
    else:
        return col.fillna('unknown')

fifa = fifa.apply(fill_na)

In [298]:
# Get the count of missing values per row
missing_per_row = fifa.isnull().sum(axis=1)

# Get the total number of rows with missing values
total_missing_rows = len(missing_per_row[missing_per_row > 0])

print(total_missing_rows)

0

### Convert position from str to int

In [299]:
POSITIONS = [  'ls' , 'st' , 'rs'  , 'lw' , 'lf'
             , 'cf' , 'rf' , 'rw'  , 'lam', 'cam'
             , 'ram', 'lm' , 'lcm' , 'cm' , 'rcm'
             , 'rm' , 'lwb', 'ldm' , 'cdm', 'rdm'
             , 'rwb', 'lb' , 'lcb' , 'cb' , 'rcb'
             , 'rb' , 'gk']

In [300]:
def split_position_skill(position_skill):
    parts = position_skill.split('+') if '+' in position_skill else position_skill.split('-') if '-' in position_skill else position_skill.split()
    general = int(parts[0])
    variation = 0 if len(parts) == 1 else int(parts[1]) if '+' in position_skill else -int(parts[1])
    return general, variation

In [301]:
%%timeit

# Convert str to int
for pos in POSITIONS:
    try:
        fifa[[pos, f'variation_{pos}']] = players_data[pos].apply(split_position_skill).apply(pd.Series)
        fifa[pos] = df[pos] + players_data[f'variation_{pos}']
        fifa.drop([f'variation_{pos}'], axis=1, inplace = True)
    except:
        break

21.2 µs ± 2.24 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

#### 1.2 Count and Replace player positions¶
If the player positions in the club is RES or SUB then his position will be replaced by the player's first position value

In [302]:
fifa['player_positions'] = fifa['player_positions'].str.split(',')
fifa['player_positions']

0        [RW,  ST,  CF]
1                  [ST]
2             [ST,  LW]
3            [LW,  CAM]
4            [CM,  CAM]
              ...
19234             [CDM]
19235              [CM]
19236              [CM]
19237              [ST]
19238             [CAM]
Name: player_positions, Length: 19239, dtype: object

In [303]:
sub_res_idx = fifa.loc[(fifa['club_position'] == 'SUB') | (fifa['club_position'] == 'RES')].index
sub_res_new_positions = fifa.loc[sub_res_idx]['player_positions'].str[0]
fifa.loc[sub_res_idx, 'club_position'] = sub_res_new_positions

In [304]:
fifa['player_positions_count'] = fifa['player_positions'].str.len()

In [305]:
fifa[['short_name', 'player_positions_count']].head()

          short_name  player_positions_count
0           L. Messi                       3
1     R. Lewandowski                       1
2  Cristiano Ronaldo                       2
3          Neymar Jr                       2
4       K. De Bruyne                       2

### Encoding relevent categorical attributes

In [306]:
# encoding relevent categorical attributes

work_rates = {'Low/Low':0,'Medium/Low':1,'Low/Medium':1,'Medium/Medium':2,'High/Low':3,'Low/High':3,'High/Medium':4,'Medium/High':4,'High/High':5}
fifa['work_rate'] = fifa['work_rate'].map(work_rates)

preferd_foot = {'Left':0,'Right':1}2
fifa['preferred_foot'] = fifa['preferred_foot'].map(preferd_foot)

body_types = {'Normal (170-)':0,'Normal (185+)':0,'Normal (170-185)':0,'Lean (170-)':1,'Lean (185+)':1,'Lean (170-185)':1,'Stocky (170-)':3,'Stocky (185+)':3,'Stocky (170-185)':3}
fifa['body_type'] = fifa['body_type'].map(body_types)

SyntaxError: invalid syntax (2392024584.py, line 6)

In [ ]:
#feature extraction process
fifa.corr()

In [ ]:
sortValues = corr_matrix['overall'].sort_values(ascending=False)

In [307]:
high_corr_data = sortValues[sortValues > abs(0.4)]

In [308]:
# select columns with correlation greater than the threshold
print(high_corr_data)

overall                     1.000000
movement_reactions          0.871823
mentality_composure         0.708867
passing                     0.663519
potential                   0.644275
dribbling                   0.618419
wage_eur                    0.601001
power_shot_power            0.561180
value_eur                   0.553823
release_clause_eur          0.532528
mentality_vision            0.523025
attacking_short_passing     0.516788
skill_long_passing          0.498216
physic                      0.491127
international_reputation    0.470647
skill_ball_control          0.460411
age                         0.459451
shooting                    0.454368
skill_curve                 0.420423
power_long_shots            0.410010
attacking_crossing          0.401356
mentality_aggression        0.400161
Name: overall, dtype: float64

### Training the model

In [309]:
features = ['overall','movement_reactions', 'mentality_composure', 'passing', 'potential', 
                        'dribbling', 'wage_eur', 'power_shot_power', 'value_eur', 'release_clause_eur', 
                      'mentality_vision', 'attacking_short_passing', 'skill_long_passing', 'physic', 'international_reputation',
                     'skill_ball_control', 'age', 'passing', 'shooting', 
                        'shooting', 'skill_curve', 'power_shot_power', 'attacking_crossing', 'mentality_aggression']

In [310]:
#Creating a new datasset with selected features
trainingData = fifa[features]
trainingData.head()

,overall,movement_reactions,mentality_composure,passing,potential,dribbling,wage_eur,power_shot_power,value_eur,release_clause_eur,...,international_reputation,skill_ball_control,age,passing,shooting,shooting,skill_curve,power_shot_power,attacking_crossing,mentality_aggression
0,93,94,96,91.0,93,95.0,320000.0,86,78000000.0,144300000.0,...,5,96,34,91.0,92.0,92.0,93,86,85,44
1,92,93,88,79.0,92,86.0,270000.0,90,119500000.0,197200000.0,...,5,88,32,79.0,92.0,92.0,79,90,71,81
2,91,94,95,80.0,91,88.0,270000.0,94,45000000.0,83300000.0,...,5,88,36,80.0,94.0,94.0,81,94,87,63
3,91,89,93,86.0,91,94.0,270000.0,80,129000000.0,238700000.0,...,5,95,29,86.0,83.0,83.0,88,80,85,63
4,91,91,89,93.0,91,88.0,350000.0,91,125500000.0,232200000.0,...,4,91,30,93.0,86.0,86.0,85,91,94,76

In [311]:
selected_features = ['movement_reactions', 'mentality_composure', 'passing', 'potential', 
                        'dribbling', 'wage_eur', 'power_shot_power', 'value_eur', 'release_clause_eur', 
                      'mentality_vision', 'attacking_short_passing', 'skill_long_passing', 'physic', 'international_reputation',
                     'skill_ball_control', 'age', 'passing', 'shooting', 
                        'shooting', 'skill_curve', 'power_shot_power', 'attacking_crossing', 'mentality_aggression']

In [312]:
X = trainingData[selected_features]
# Choose target and features
y = trainingData.overall

In [313]:
from sklearn.model_selection import train_test_split

# split data into training and validation data, for both features and target
# The split is based on a random number generator. Supplying a numeric value to
# the random_state argument guarantees we get the same split every time we
# run this script.
train_X, val_X, train_y, val_y = train_test_split(X, y,random_state = 0)

In [314]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

forest_model = RandomForestRegressor(random_state=1)
forest_model.fit(train_X, train_y)
predicted_rating = forest_model.predict(val_X)
print(predicted_rating)

[62.   64.99 73.94 ... 71.99 67.96 69.41]

In [315]:
print(mean_absolute_error(val_y, predicted_rating))

0.2993555093555096

In [316]:
# We will evaluate the model by 
# strike the right balance and choose the optimal max_feature
forest_model = RandomForestRegressor(n_estimators=100, max_depth=5, max_features=10, random_state=1)
forest_model.fit(train_X, train_y)
predicted_rating = forest_model.predict(val_X)
print(predicted_rating)

[63.63220355 65.19269897 72.50156063 ... 68.0536678  68.05937175
 69.21838227]

In [317]:
print(mean_absolute_error(val_y, predicted_rating))

1.111505559323048

In [318]:
testing_data = pd.read_csv('players_17.csv')

In [319]:
testingData = testing_data[selected_features]
testingData.head()

,movement_reactions,mentality_composure,passing,potential,dribbling,wage_eur,power_shot_power,value_eur,release_clause_eur,mentality_vision,...,international_reputation,skill_ball_control,age,passing,shooting,shooting,skill_curve,power_shot_power,attacking_crossing,mentality_aggression
0,96,86,81.0,94,91.0,575000.0,94,87000000.0,NaN,85,...,5,92,31,81.0,92.0,92.0,81,94,84,63
1,95,94,86.0,93,96.0,575000.0,83,89000000.0,NaN,90,...,5,95,29,86.0,90.0,90.0,89,83,77,48
2,85,70,NaN,92,NaN,225000.0,25,69500000.0,NaN,70,...,5,48,30,NaN,NaN,NaN,14,25,15,29
3,93,83,79.0,92,87.0,525000.0,87,83000000.0,NaN,84,...,5,91,29,79.0,90.0,90.0,86,87,77,78
4,88,80,78.0,95,95.0,450000.0,78,109000000.0,NaN,80,...,5,95,24,78.0,84.0,84.0,78,78,75,56

In [321]:
y_pred = forest_model.predict(testingData)

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names must be in the same order as they were in fit.

  warnings.warn(message, FutureWarning)

ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

In [ ]:
# Split the new dataset into features and target variable
X_new = testing_data[selected_features]
y_new = testing_data['overall']

In [ ]:
# Make predictions on the new data
# Apply the same preprocessing steps used for the training data
X_new_processed = scaler.transform(X_new)
X_new_processed = pd.DataFrame(X_new_processed, columns=X_new.columns)
X_new_processed = encoder.transform(X_new_processed)
y_pred = forest_model.predict(X_new)